# Generated by Django 4.2.2 on 2023-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ing',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
